using System;

namespace Gravitas.CollisionCoordination.Models
{
    public class LaboratoryDataVm
    {
        public DateTime? CheckOutDateTime { get; set; }
        public string ProductName { get; set; }
        public string SenderName { get; set; }
        public string SingleWindowComment { get; set; }
        public string LaboratoryComment { get; set; }
        public string AutoGeneratedComment { get; set; }
        public string TransportNo { get; set; }
        public string TrailerNo { get; set; }
        public string AnalysisReleaseUserName { get; set; }
        public float? ImpurityValue { get; set; }
        public float? HumidityValue { get; set; }
        public string IsInfectionedClassId { get; set; }
        public float? EffectiveValue { get; set; }
        public string ApproveLink { get; set; }
        public string DisapproveLink { get; set; }
        public string DisplayButtons { get; set; }
        public string LaboratoryEmail { get; set; }
        public string LaboratoryWorker { get; set; }
        public string LabolatoryFilePath { get; set; }
        public string Phone1 { get; set; }
        public string Email1 { get; set; }
        public string Phone2 { get; set; }
        public string Email2 { get; set; }
        public string Phone3 { get; set; }
        public string Email3 { get; set; }
    }
}