using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Gravitas.Platform.Web.ViewModel
{
    public static partial class CentralLaboratoryProcess
    {
        public class CentralLabolatorySamplePrintoutVm
        {
            [DisplayName("Час відбору проби")]
            //public DateTime? SampleCollectDateTime { get; set; }
            public DateTime? CheckOutDateTime { get; set; }

            [DisplayName("Продукт")] public string ProductName { get; set; }
            [DisplayName("Відправник")] public string SenderName { get; set; }
            [DisplayName("Коментар (Авто)")] public string CommentAutoGenerated { get; set; }
            [DisplayName("Коментар (ТТН)")] public string SingleWindowComment { get; set; }

            [DisplayName("Транспорт No.")] public string TransportNo { get; set; }
            [DisplayName("Причеп No.")] public string TrailerNo { get; set; }

            [DisplayName("Лаборант відбору проб")] public string SampleCollectUserName { get; set; }

            [DisplayName("Лаборант закінчення аналізів")]
            public string AnalysisReleaseUserName { get; set; }

            public PrintoutOpVisaItemsVm OpVisaItems { get; set; }
        }
    }
}