// <auto-generated />
namespace Gravitas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RouteEditorChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RouteEditorChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201809281433135_Route-Editor-Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
