// <auto-generated />
namespace Gravitas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBarCoreSingleWindowOpData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBarCoreSingleWindowOpData));
        
        string IMigrationMetadata.Id
        {
            get { return "201902260708417_Add-BarCore-SingleWindowOpData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
