// <auto-generated />
namespace Gravitas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSingleWindowIsPreRegistered : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSingleWindowIsPreRegistered));
        
        string IMigrationMetadata.Id
        {
            get { return "201905130601289_Add-SingleWindow-IsPreRegistered"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
