// <auto-generated />
namespace Gravitas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class AddValves : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddValves));
        
        string IMigrationMetadata.Id
        {
            get { return "202105141512331_Add-Valves"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
