CREATE TABLE [mhp].[opd].[ScaleOpDataHistory] (
    [Id]                      UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
	[ScaleOpDataId]			  UNIQUEIDENTIFIER NOT NULL,
	[LogType]				  CHAR(1)		   NULL,
    [LogDateTime]			  DATETIME		   DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    [TypeId]                  BIGINT           NOT NULL,
    [TruckWeightDateTime]     DATETIME         NULL,
    [TruckWeightValue]        FLOAT (53)       NULL,
    [TruckWeightIsAccepted]   BIT              NULL,
    [TrailerWeightDateTime]   DATETIME         NULL,
    [TrailerWeightValue]      FLOAT (53)       NULL,
    [TrailerWeightIsAccepted] BIT              NULL,
    [StateId]                 BIGINT           NOT NULL,
    [NodeId]                  BIGINT           NULL,
    [TicketId]                BIGINT           NULL,
    [TicketContainerId]       BIGINT           NULL,
    [CheckInDateTime]         DATETIME2 (7)    NULL,
    [CheckOutDateTime]        DATETIME2 (7)    NULL,
    [TrailerAvailable]        BIT              DEFAULT ((0)) NOT NULL,
    [GuardPresence]           BIT              DEFAULT ((0)) NOT NULL,    
);