using System;

namespace Gravitas.Model
{
    public class SingleWindowOpData : BaseOpData
    {
        public string ContactPhoneNo { get; set; }
        public double LoadTarget { get; set; }
        public int LoadTargetDeviationPlus { get; set; }
        public int LoadTargetDeviationMinus { get; set; }
        public string OrganizationId { get; set; }
        public string OrganizationTitle { get; set; }
        public string ProductTitle { get; set; }
        public string CreateOperatorId { get; set; }
        public DateTime? CreteDate { get; set; }
        public string EditOperatorId { get; set; }
        public DateTime? EditDate { get; set; }
        public string DocumentTypeId { get; set; }
        public string StockId { get; set; }
        public string ReceiverTypeId { get; set; }
        public string ReceiverId { get; set; }
        public string ReceiverTitle { get; set; }   
        public string ReceiverAnaliticsId { get; set; }
        public string ProductId { get; set; }
        public string HarvestId { get; set; }
        public double? GrossValue { get; set; }
        public double? TareValue { get; set; }
        public double? NetValue { get; set; }
        public string DriverOneId { get; set; }
        public string DriverTwoId { get; set; }
        public string TransportId { get; set; }
        public string HiredDriverCode { get; set; }
        public string HiredTransportNumber { get; set; }
        public string IncomeInvoiceSeries { get; set; }
        public string IncomeInvoiceNumber { get; set; }
        public string ReceiverDepotId { get; set; }
        public bool IsThirdPartyCarrier { get; set; }
        public string CarrierCode { get; set; }
        public string BuyBudgetId { get; set; }
        public string SellBudgetId { get; set; }
        public double? PackingWeightValue { get; set; }
        public string KeeperOrganizationId { get; set; }
        public string OrderCode { get; set; }
        public string SupplyCode { get; set; }
        public string SupplyTypeId { get; set; }
        public DateTime? RegistrationDateTime { get; set; }
        public DateTime? InTime { get; set; }
        public DateTime? OutTime { get; set; }
        public DateTime? FirstGrossTime { get; set; }
        public DateTime? FirstTareTime { get; set; }
        public DateTime? LastGrossTime { get; set; }
        public DateTime? LastTareTime { get; set; }
        public string CollectionPointId { get; set; }
        public string LabHumidityName { get; set; }
        public string LabImpurityName { get; set; }
        public bool LabIsInfectioned { get; set; }
        public double? LabHumidityValue { get; set; }
        public double? LabImpurityValue { get; set; }
        public double? DocHumidityValue { get; set; }
        public double? DocImpurityValue { get; set; }
        public double? DocNetValue { get; set; }
        public DateTime? DocNetDateTime { get; set; }
        public string ReturnCauseId { get; set; }
        public string TrailerId { get; set; }
        public string TrailerNumber { get; set; }
        public string TripTicketNumber { get; set; }
        public DateTime? TripTicketDateTime { get; set; }
        public string WarrantSeries { get; set; }
        public string WarrantNumber { get; set; }
        public DateTime? WarrantDateTime { get; set; }
        public string WarrantManagerName { get; set; }
        public string StampList { get; set; }
        public string StatusType { get; set; }
        public string RuleNumber { get; set; }
        public double? TrailerGrossValue { get; set; }
        public double? TrailerTareValue { get; set; }
        public double? IncomeDocGrossValue { get; set; }
        public double? IncomeDocTareValue { get; set; }
        public DateTime? IncomeDocDateTime { get; set; }
        public string Comments { get; set; }
        public double? WeightDeltaValue { get; set; }
        public string SupplyTransportTypeId { get; set; }
        public string LabolatoryOperatorId { get; set; }
        public string GrossOperatorId { get; set; }
        public long ScaleInNumber { get; set; }
        public long ScaleOutNumber { get; set; }
        public string BatchNumber { get; set; }
        public string TareOperatorId { get; set; }
        public string LoadingOperatorId { get; set; }
        public DateTime? LoadOutDateTime { get; set; }
        public string CarrierRouteId { get; set; }
        public double? LabOilContentValue { get; set; }
        public string DeliveryBillId { get; set; }
        public string DeliveryBillCode { get; set; }
        public string InformationCarrier { get; set; }
        public string CustomPartnerName { get; set; }
        public string CarrierId { get; set; }
        public string ProductContents { get; set; }
        public string BarCode { get; set; }
        public string OriginalТТN { get; set; }
        public string HiredTrailerNumber { get; set; }
        public string ContractCarrierId { get; set; }
        public double? SenderWeight { get; set; }
        public bool IsPreRegistered { get; set; }
        public DateTime? PredictionEntranceTime { get; set; }
    }
}