using System;
using Gravitas.Model.DomainModel.OpData.DAO.Base;

namespace Gravitas.Model.DomainModel.OpData.DAO
{
    public class SingleWindowOpData : BaseOpData
    {
        public string ContactPhoneNo { get; set; }
        public double LoadTarget { get; set; }
        public int LoadTargetDeviationPlus { get; set; }
        public int LoadTargetDeviationMinus { get; set; }
        public Guid? OrganizationId { get; set; }
        public string OrganizationTitle { get; set; }
        public string ProductTitle { get; set; }
        public Guid? CreateOperatorId { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? EditOperatorId { get; set; }
        public DateTime? EditDate { get; set; }
        public string DocumentTypeId { get; set; }
        public Guid? StockId { get; set; }
        public Guid? ReceiverTypeId { get; set; }
        public Guid? ReceiverId { get; set; }
        public string ReceiverTitle { get; set; }   
        public Guid? ReceiverAnaliticsId { get; set; }
        public Guid? ProductId { get; set; }
        public Guid? HarvestId { get; set; }
        public double? GrossValue { get; set; }
        public double? TareValue { get; set; }
        public double? NetValue { get; set; }
        public Guid? DriverOneId { get; set; }
        public Guid? DriverTwoId { get; set; }
        public Guid? TransportId { get; set; }
        public string HiredDriverCode { get; set; }
        public string TransportNumber { get; set; }
        public string IncomeInvoiceSeries { get; set; }
        public string IncomeInvoiceNumber { get; set; }
        public Guid? ReceiverDepotId { get; set; }
        public bool IsThirdPartyCarrier { get; set; }
        public string CarrierCode { get; set; }
        public Guid? BuyBudgetId { get; set; }
        public Guid? SellBudgetId { get; set; }
        public double? PackingWeightValue { get; set; }
        public Guid? KeeperOrganizationId { get; set; }
        public string OrderCode { get; set; }
        public string SupplyCode { get; set; }
        public Guid? SupplyTypeId { get; set; }
        public DateTime? RegistrationDateTime { get; set; }
        public DateTime? InTime { get; set; }
        public DateTime? OutTime { get; set; }
        public DateTime? FirstGrossTime { get; set; }
        public DateTime? FirstTareTime { get; set; }
        public DateTime? LastGrossTime { get; set; }
        public DateTime? LastTareTime { get; set; }
        public Guid? CollectionPointId { get; set; }
        public string LabHumidityName { get; set; }
        public string LabImpurityName { get; set; }
        public bool LabIsInfectioned { get; set; }
        public double? LabHumidityValue { get; set; }
        public double? LabImpurityValue { get; set; }
        public double? DocHumidityValue { get; set; }
        public double? DocImpurityValue { get; set; }
        public double? DocNetValue { get; set; }
        public DateTime? DocNetDateTime { get; set; }
        public string ReturnCauseId { get; set; }
        public Guid? TrailerId { get; set; }
        public string TripTicketNumber { get; set; }
        public DateTime? TripTicketDateTime { get; set; }
        public string WarrantSeries { get; set; }
        public string WarrantNumber { get; set; }
        public DateTime? WarrantDateTime { get; set; }
        public string WarrantManagerName { get; set; }
        public string StampList { get; set; }
        public string StatusType { get; set; }
        public string RuleNumber { get; set; }
        public double? TrailerGrossValue { get; set; }
        public double? TrailerTareValue { get; set; }
        public double? IncomeDocGrossValue { get; set; }
        public double? IncomeDocTareValue { get; set; }
        public DateTime? IncomeDocDateTime { get; set; }
        public string Comments { get; set; }
        public double? WeightDeltaValue { get; set; }
        public string SupplyTransportTypeId { get; set; }
        public Guid? LabolatoryOperatorId { get; set; }
        public Guid? GrossOperatorId { get; set; }
        public int ScaleInNumber { get; set; }
        public int ScaleOutNumber { get; set; }
        public string BatchNumber { get; set; }
        public Guid? TareOperatorId { get; set; }
        public Guid? LoadingOperatorId { get; set; }
        public DateTime? LoadOutDateTime { get; set; }
        public string CarrierRouteId { get; set; }
        public double? LabOilContentValue { get; set; }
        public string DeliveryBillId { get; set; }
        public string DeliveryBillCode { get; set; }
        public string InformationCarrier { get; set; }
        public string CustomPartnerName { get; set; }
        public Guid? CarrierId { get; set; }
        public string ProductContents { get; set; }
        public string BarCode { get; set; }
        public string OriginalТТN { get; set; }
        public string TrailerNumber { get; set; }
        public Guid? ContractCarrierId { get; set; }
        public double? SenderWeight { get; set; }
        public int DriverPhotoId { get; set; }
    }
}