using Gravitas.DAL.Repository._Base;
using Gravitas.Model.DomainModel.ExternalData.AcceptancePoint.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Budget.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Budget.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.Contract.DTO;
using Gravitas.Model.DomainModel.ExternalData.Crop.DTO;
using Gravitas.Model.DomainModel.ExternalData.DeliveryBill.DTO;
using Gravitas.Model.DomainModel.ExternalData.Employee.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Employee.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.ExternalUser.DTO;
using Gravitas.Model.DomainModel.ExternalData.FixedAsset.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.FixedAsset.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.LabClassifier.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.LabClassifier.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.MeasureUnit.DTO;
using Gravitas.Model.DomainModel.ExternalData.Organization.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Organization.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.Partner.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Partner.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.Product.DTO;
using Gravitas.Model.DomainModel.ExternalData.Product.List;
using Gravitas.Model.DomainModel.ExternalData.ReasonForRefund.DTO;
using Gravitas.Model.DomainModel.ExternalData.Route.DTO;
using Gravitas.Model.DomainModel.ExternalData.Stock.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.Stock.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.Subdivision.DTO;
using Gravitas.Model.DomainModel.ExternalData.SupplyTransportType.DTO.Detail;
using Gravitas.Model.DomainModel.ExternalData.SupplyTransportType.DTO.List;
using Gravitas.Model.DomainModel.ExternalData.SupplyType.DTO;
using Gravitas.Model.DomainModel.ExternalData.YearOfHarvest.DTO;

namespace Gravitas.DAL.Repository.ExternalData
{
    public interface IExternalDataRepository : IBaseRepository
    {
        AcceptancePointDetail GetAcceptancePointDetail(string id);
        BudgetDetail GetBudgetDetail(string id);
        ContractDetail GetContractDetail(string id);
        CropDetail GetCropDetail(string id);
        DeliveryBillStatusDetail GetDeliveryBillStatusDetail(string id);
        DeliveryBillTypeDetail GetDeliveryBillTypeDetail(string id);
        EmployeeDetail GetEmployeeDetail(string id);
        ExternalEmployeeDetail GetExternalEmployeeDetail(string id);
        FixedAssetDetail GetFixedAssetDetail(string id);
        LabImpurityСlassifierDetail GetLabImpurityСlassifierDetail(string id);
        LabHumidityСlassifierDetail GetLabHumidityСlassifierDetail(string id);
        LabInfectionedСlassifierDetail GetLabInfectionedСlassifierDetail(string id);
        MeasureUnitDetail GetMeasureUnitDetail(string id);
        OriginTypeDetail GetOriginTypeDetail(string id);
        OrganisationDetail GetOrganisationDetail(string id);
        PartnerDetail GetPartnerDetail(string id);
        ProductDetail GetProductDetail(string id);
        ReasonForRefundDetail GetReasonForRefundDetail(string id);
        RouteDetail GetRouteDetail(string id);
        StockDetail GetStockDetail(string id);
        SubdivisionDetail GetSubdivisionDetail(string id);
        SupplyTransportTypeDetail GetSupplyTransportTypeDetail(string id);
        SupplyTypeDetail GetSupplyTypeDetail(string id);
        YearOfHarvestDetail GetYearOfHarvestDetail(string id);
        ProductItems GetProductChildItems(string id);
        ProductItems GetProductItems();
        BudgetItems GetBudgetItems();
        EmployeeItems GetEmployeeItems();
        OrganisationItems GetOrganisationItems();
        FixedTrailerItems GetFixedTrailerItems(int pageNo, int perPageNo);
        PartnerItems GetFilteredPagePartnerItems(int pageNo, int perPageNo, string filter);
        EmployeeItems GetFilteredPageEmployeeItems(int pageNo, int perPageNo, string filter);
        StockItems GetFilteredPageStockItems(int pageNo, int perPageNo, string filter);
        FixedTrailerItems GetFilteredPageFixedTrailerItems(int pageNo, int perPageNo, string filter);
        FixedAssetItems GetFilteredPageFixedAssetItems(int pageNo, int perPageNo, string filter);
        ProductItems GetFilteredPageProductItems(int pageNo, int perPageNo, string filter);
        PartnerItems GetPartnerItems();
        StockItems GetStockItems();
        SupplyTransportTypeItems GetSupplyTransportTypeItems();
        LabHumidityСlassifierItems GetLabHumidityСlassifierItems();
        LabImpurityСlassifierItems GetLabImpurityСlassifierItems();
        LabInfectionedСlassifierItems GetLabInfectionedСlassifierItems();
        LabDeviceResultTypeItems GetLabDevResultTypeItems();
        BudgetItems GetBudgetChildItem(string parentId);
        PartnerItems GetPartnerChildItems(string parentId);
        EmployeeItems GetEmployeeChildItems(string parentId);
    }
}