using System;
using System.ComponentModel;

namespace Gravitas.Platform.Web.ViewModel {

	public static partial class LaboratoryInVms {

		public class SamplePrintoutVm {
			[DisplayName("Час відбору проби")]
			//public DateTime? SampleCollectDateTime { get; set; }
			public DateTime? CheckOutDateTime { get; set; }

			[DisplayName("Продукт")]
			public string ProductName { get; set; }
			[DisplayName("Відправник")]
			public string SenderName { get; set; }
			[DisplayName("Коментар (Авто)")]
			public string CommentAutoGenerated { get; set; }
			[DisplayName("Коментар (ТТН)")]
			public string CommentSingleWindow { get; set; }

			[DisplayName("Транспорт No.")]
			public string TransportNo { get; set; }
			[DisplayName("Причеп No.")]
			public string TrailerNo { get; set; }

			[DisplayName("Лаборант відбору проб")]
			public string SampleCollectUserName { get; set; }
			[DisplayName("Лаборант закінчення аналізів")]
			public string AnalysisReleaseUserName { get; set; }

			public string HumidityValueUserName { get; set; }
			public string ImpurityValueUserName { get; set; }
			public string EffectiveValueUserName { get; set; }
			public string IsInfectionedValueUserName { get; set; }

			[DisplayName("Засміченість")]
			public float? ImpurityValue { get; set; }
			public string ImpurityClassId { get; set; }
			[DisplayName("Вологість")]
			public float? HumidityValue { get; set; }
			public string HumidityClassId { get; set; }
			[DisplayName("Зараженість")]
			public string IsInfectionedClassId { get; set; }
			[DisplayName("Протеїн\\Масличніст")]
			public float? EffectiveValue { get; set; }
			public string EffectiveClassifier { get; set; }

			public PrintoutOpVisaItemsVm OpVisaItems { get; set; }
		}
	}
}